version: "3"

includes:
  rust:
    taskfile: ./.taskfile/rust.yml
  markdown:
    taskfile: ./.taskfile/markdown.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  format:
    desc: Format all code
    cmds:
      - task: rust:format
      - task: markdown:format

  lint:
    desc: Lint all code
    cmds:
      - task: rust:lint
      - task: markdown:lint

  check:
    desc: Run all checks (format check + lint)
    cmds:
      - task: rust:check
      - task: markdown:check

  fix:
    desc: Fix all auto-fixable issues
    cmds:
      - task: rust:fix
      - task: markdown:fix
